# ---------- Metadata ----------
project_name: autoencoder
run_name: vae_latent16_lr1e3_seed1
seed: 234

# ---------- Model ----------
model:
  type: Autoencoder
  variant: beta
  input_dim: 784
  latent_dim: 32
  hidden_dim: 128
  activation: relu

# ---------- Training ----------
training:
  epochs: 100
  lr: .0001
  batch_size: 64
  weight_decay: 0.0
  grad_clip: 1.0
  log_interval: 1             # log loss every N epochs
  diagnostic_interval: 10     # run diagnostics every N epochs
  save_checkpoints: true

# ---------- Loss Weights ----------
loss:
  type: ae
  recon_type: mse
  reconstruction_weight: 1.0
  kl_weight: 0.1
  jacobian_penalty: 0.0       # optionally used during training

# ---------- Optimizer / Scheduler ----------
optimizer:
  type: Adam
  parameters: 
scheduler:
  enabled: True
  step_size: 20
  gamma: 0.5
  log: True

# ---------- Data ----------
data:
  task: reconstruction
  dataset: MNIST
  path: data/
  val_split: 0.1
  batch_size: 64
  shuffle: true
  num_workers: 8
  normalize: true
  augment: false

# ---------- Diagnostics ----------
diagnostics:
#NOTE THESE MUST BE THE METHOD NAMES NOT THE FILE NAMES. 
  - tensor_stats_diag
  - layer_pca
  - log_reconstruction_plot
  - jacobian_norm_diag
diagnostics_config:
  tensor_stats_diag_keys: ["latent", "recon"]
  tensor_stats_diag_suffixes: ["mean", "std", "min", "max"]
  jacobian_norm_diag_keys: ["latent", "recon"]
  jacobian_norm_diag_suffixes: ["spectral", "jacfro"]
  layer_pca_keys: ["latent"]
# ---------- Logging ----------
logging:
  use_wandb: true
  offline_mode: false
  save_artifacts: true
  verbose: true